### ISSUE TITLE
Using EloquentTinyML only a few functions are working

### ISSUE THREAD

**Issue by GabeFigenio** [eloquentarduino/tflm_esp32#3]
I'm using EloquentTinyML with tflm_esp32 and only a few functions are declare to use, such as Softmax, Relu and FullyConnected. But I need to use Logistic, Transpose, While and others. This other functions works on ESP32? My guess is that the problem is on EloquentTinyML, but I want to be sure.

**Comment by eloquentarduino** [comment]
Replied at [https://github.com/eloquentarduino/EloquentTinyML/issues/74](https://github.com/eloquentarduino/EloquentTinyML/issues/74)
